# Generated by Django 5.0 on 2023-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spammer_name', models.CharField(max_length=100, verbose_name='ФИО менеджера')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Компания')),
                ('is_active', models.BooleanField(default=True, verbose_name='действителен')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
    ]
