# Generated by Django 5.0 on 2023-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spammer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email менеджера'),
        ),
    ]
