# Generated by Django 5.0 on 2023-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammer', '0002_spammer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='ФИО менеджера')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email менеджера')),
                ('is_active', models.BooleanField(default=True, verbose_name='действителен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
