# Generated by Django 5.0 on 2023-12-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammer', '0004_client_spammer_alter_client_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='spammer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spammer_in_client', to='spammer.spammer', verbose_name='ФИО менеджера'),
        ),
    ]
